Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Modules\Social\Http\Controllers\OAuthController;
use Modules\Social\Http\Controllers\SocialController;

// oauth
Route::get('/oauth/{driver}', [OAuthController::class, 'redirectToProvider'])->name('oauth');
Route::get('/callback/oauth/{driver}', [OAuthController::class, 'handleProviderCallback']);

Route::middleware('admin:social')->group(function () {

    Route::resource('user-social', SocialController::class);

});

Resources/views/userSocialites/create.blade.php
@extends('core::layouts.master')

@section('content')
    <div class="layui-card">
        <div class="layui-card-header">新增</div>
        <div class="layui-card-body">
            <x-form :action="route('user-social.store')" method="post">

                <div class="layui-row layui-col-space10">
                    @include('core::userSocialites.fields')
                </div>

            </x-form>
        </div>
    </div>
@endsection

Resources/views/userSocialites/edit.blade.php
@extends('core::layouts.master')

@section('content')
	<div class="layui-card layui-form">
		<div class="layui-card-header">编辑#{{ $userSocialite->id }}</div>
		<div class="layui-card-body">
            <x-form :action="route('user-social.update', $userSocialite->id)" method="patch">

				<div class="layui-row layui-col-space10 layui-form-item">
					@include('core::userSocialites.fields')
				</div>

			</x-form>
		</div>
	</div>
@endsection

Resources/views/userSocialites/fields.blade.php
<x-input name="driver" :value="$role->driver??''"/>
<x-input name="userid" :value="$role->userid??''"/>
<x-input name="oid" :value="$role->oid??''"/>
<x-input name="openid" :value="$role->openid??''"/>
<x-input name="anonymous_openid" :value="$role->anonymous_openid??''"/>
<x-input name="token" :value="$role->token??''"/>
<x-input name="nickname" :value="$role->nickname??''"/>
<x-input name="avatar" :value="$role->avatar??''"/>
<x-input name="gender" :value="$role->gender??''"/>
<x-input name="country" :value="$role->country??''"/>
<x-input name="province" :value="$role->province??''"/>
<x-input name="city" :value="$role->city??''"/>

<div class="layui-form-item layui-layout-admin">
    <div class="layui-input-block">
		<div class="layui-footer z-50" style="left:0;">
			<button class="layui-btn" lay-submit lay-filter="component-form-demo1">{{__('submit')}}</button>
			<button type="reset" class="layui-btn layui-btn-primary">{{__('cancel')}}</button>
		</div>
    </div>
</div>

@push('script')
	<script>
		layui.use('form', function(){
			var form = layui.form
		})
	</script>
@endpush

Resources/views/userSocialites/index.blade.php
@extends('core::layouts.master')

@section('content')
    <x-wd-submenu :items="
    [
    ['name' => '粉丝管理', 'uri' => route('user-social.index')]
   ]" />

    <table class="layui-hide" id="data_usersocialite_table" lay-filter="data_usersocialite_table"></table>
@endsection


@push('script')
    <script type="text/html" id="tpl_driver">
        @{{# if(d.driver == 'toutiao'){ }}
        <span class="layui-badge bg-red-500">头条</span>
        @{{# }else if(d.driver == 'wechat'){ }}
        <span class="layui-badge bg-green-600">微信</span>
        @{{# }else if(d.driver == 'feishu'){ }}
        <span class="layui-badge bg-blue-600">飞书</span>
        @{{# }else{ }}
        <span class="layui-badge bg-gray-600">@{{ d.driver  }}</span>
        @{{# } }}
    </script>
    <script>
        layui.use(['table', 'element'], function(){
            var table = layui.table,
                admin = parent.layui == layui?layui.admin:parent.layui.admin,
                element = layui.element;

            table.render({
                elem: '#data_usersocialite_table',
                url: '{!! URL::full() !!}',
                autoShow: '{{ route('user-social.show', '_id_') }}',
                where: {'orderBy': 'created_at', 'sortedBy': 'desc'},
                page: true,
                canSearch: true,
                toolbar: [],
                height: 'full-110',
                cellMinWidth: 80,
                cols: [[
                    {"type":"checkbox","fixed":"left"},
                    {"field":"create_by","title":"UserId"},
                    {"field":"driver","title":"driver",templet: '#tpl_driver'},
                    {"field":"nickname","title":"nickname",width:150},
                    {"field":"avatar","title":"avatar",templet: '<div><img src="@{{ d.avatar }}" width="30"/></div>',width:90},
                    {"field":"openid","title":"openid",width:150},
                    {"field":"anonymous_openid","title":"anonymous_openid"},
                    {"field":"token","title":"token"},
                    {"field":"gender","title":"gender"},{"field":"country","title":"country"},{"field":"province","title":"province"},{"field":"city","title":"city"},{"field":"created_at","title":"创建时间"},{"field":"updated_at","title":"更新时间","fixed":"right"}]]
            });

            //监听行工具事件
            table.on('toolbar(data_usersocialite_table)', function(obj){
                var checked = table.checkStatus('data_usersocialite_table');

                if(obj.event == 'create') {
                    admin.openTab('{{ route('user-social.create') }}', '新增数据')
                    return true;
                }

                if((obj.event == 'delete'|| obj.event == 'update') && checked.data.length >0 ) {
                    if(checked.data.length !== 1) {
                        layer.msg('请选择一条数据!');
                        return false;
                    }

                    if(obj.event === 'delete') {
                        layer.confirm('真的删除行么', function(index){
                            layui.util.request.post('{{ route('user-social.destroy', '_id_') }}'.replace('_id_', checked.data[0].id), {'_method': 'DELETE'}, function(res){
                                layer.msg('删除成功');
                                table.reload('data_usersocialite_table')
                            })

                            layer.close(index);
                        });
                    }else if(obj.event === 'update') {
                        admin.openTab('{{route('user-social.edit', '_id_')}}'.replace('_id_', checked.data[0].id), '修改数据#'+checked.data[0].id)
                        return true;
                    }
                }
            });

        });
    </script>
@endpush